choco install zoom -y
choco install adobereader -y
choco install office365business -y
choco install javaruntime -y
choco install git -y
choco install vscode -y
choco install sysinternals -y
choco install notepadplusplus -y
choco install python -y
choco install firefox -y